- "a"
- "an"
- "and"
- "as"
- "at"
- "but"
- "by"
- "de"
- "for"
- "for"
- "from"
- "if"
- "in"
- "nor"
- "of"
- "off"
- "on"
- "or"
- "out"
- "pas"
- "per"
- "so"
- "the"
- "to"
- "up"
- "via"
- "with"
- "yet"
