minor:
  - "a"
  - "an"
  - "and"
  - "as"
  - "at"
  - "but"
  - "by"
  - "de"
  - "for"
  - "if"
  - "in"
  - "nor"
  - "of"
  - "on"
  - "or"
  - "pas"
  - "per"
  - "so"
  - "the"
  - "to"
  - "up"
  - "via"
  - "with"
  - "yet"
